### ISSUE TITLE
CUDPSender::Send failed with: 'Permission denied'

### ISSUE THREAD

**Issue by lin0303-siyuan** [eclipse-ecal/ecal#1014]
### Problem Description

I try to use CRIU to checkpoint the current status of the subscriber, and would like to resume later. 

My command is 
```mkdir ckp && criu dump -D ckp -j -t ${SUBSCRIBER_PID}```. 

And next, I want to resume the subscriber  process, 
```criu restore -D ckp -j```. 

It seems that the subscriber always outputs "CUDPSender::Send failed with: 'Permission denied" twice every time it outputs the correct message . Like this 
![image](https://user-images.githubusercontent.com/55444159/225211643-9f422a31-6153-4515-81a2-6cb3a4ad3f2e.png)

I use `sudo` to run the application, but it still doesn't work. Thus I have no idea how it is going.  I'd really appreciate it if you can offer some guidance!

### How to reproduce

Here is the source code for the subscriber:
```cpp
#include <ecal/ecal.h>
#include <ecal/msg/string/subscriber.h>

#include <iostream>
#include <thread>

void client_call_back(const std::string &message) {
  std::cout << "Received Message: " << message << std::endl;
}

int main(int argc, char **argv) {
  // initialize eCAL
  eCAL::Initialize(argc, argv, "Client Subscriber");

  // create a client subscriber that listens on "gte"
  eCAL::string::CSubscriber<std::string> subscriber("gtee");

  // Set the Callback
  subscriber.AddReceiveCallback(
      std::bind(&client_call_back, std::placeholders::_2));

  while (eCAL::Ok()) {
    std::this_thread::sleep_for(std::chrono::milliseconds(1000));
  }

  // finalize eCAL API
  eCAL::Finalize();
  return 0;
}
```
Here is the source code for the publisher:
```cpp
#include <ecal/ecal.h>
#include <ecal/msg/string/publisher.h>

#include <iostream>
#include <thread>

int main(int argc, char **argv) {
  // initialize eCAL
  eCAL::Initialize(argc, argv, "Server Publisher");

  // create a server publisher that publish on "gte"
  eCAL::string::CPublisher<std::string> publisher("gtee");
  // Set the Callback

  int counter = 0;
  while (eCAL::Ok()) {
    std::this_thread::sleep_for(std::chrono::milliseconds(1000));
    std::string message = "Hello World " + std::to_string(++counter);
    std::cout << "Sending message: " << message << std::endl;
    publisher.Send(message);
  }
  // finalize eCAL API
  eCAL::Finalize();
  return 0;
}
```

### How did you get eCAL?

Ubuntu PPA (apt-get)

### Environment

* eCAL: v5.11.3
* OS: Ubuntu
* build with C++ 14
* CRIU version: 3.6

**Comment by lin0303-siyuan** [comment]
It seems that the output of "permission denied" is correlated with publisher sleep time inside the loop. If I let the publisher wait for 3 seconds per sending message, it will print 6 times "permission denied". I don't know why they are connected and how I can fix the issue.

**Comment by KerstinKeller** [comment]
So we have never before worked with CRIU.
eCAL programs have a lot of resources (e.g. shared memory files, mutexes) which are shared between a publisher and a subscriber. Both entities negotiate where and how data will be exchanged and keep file handles to these resources.
There are other resources like open sockets for multicast udp traffic.

If you now just halt the program of the subscriber and dump it, and try to restore it later, I honestly have no idea what will happen to all these resources.
The publisher might clean them up, because to him there are no more active subscribers. 
The OS might clean them up, if nobody is using them.

I assume that there is some problem with a UDP socket, since you get `CUDPSender::Send` failed.

And apart from this as mentioned previously:
for eCAL communication to work, you need negotiations between publishers and subscribers. If you just freeze them and spin them up at a later random point, I highly doubt that things will go well...

**Comment by KerstinKeller** [comment]
And another note:
Please don't start eCAL applications with sudo permissions, or if you do, please be aware that tasks started with sudo cannot communicate with started without sudo on the same machine using shared memory.
The memory files are created in user space (which is root for those applications started with sudo) and then non sudo applications won't be able to access them (and vice versa).
