### ISSUE TITLE
eCAL Measurement Cutter creates *.ecalmeas file in wrong directory

### ISSUE THREAD

**Issue by julien-seitz** [eclipse-ecal/ecal#1109]
### Problem Description

When cutting a measurement with the measurement cutter script, then the *.ecalmeas file will be created in a subfolder "MEASUREMENT_CONVERTER" of the measurement. However, it should be created in the top level folder. This would be the behaviour of the eCAL Recorder:

MeasCutter Folder Structure:

Recording_Folder
+ MEASUREMENT_CONVERTER
    + doc
        + ...
    + *.ecalmeas
    + *.hdf5
+ config.yaml

Current eCAL Recorder Folder Structure:

Recording_Folder
+ doc
+ PC1
    + *.hdf5
+ PC2
    + *.hdf5
+ *.ecalmeas

### How to reproduce

Cutting an measurement with ecal cutter

### How did you get eCAL?

I don't know

### Environment

Windows 64 bit
eCAL 5.10.2

**Comment by hannemn** [comment]
Hi @julien-seitz ,
thanks for the bug report. When providing the measurement root path (location of *.ecalmeas) to meas cutter, it technically invokes at some point the eCAL HDF5 API that recursively opens all *.hdf5 files in the subfolders like PC1, PC2, etc. But from API perspective the opened becomes shown and abstracted as one single big measurement. It means that the folder structure as well as in particular the folder names, where the hdf5 files has been orginally recorded are not exposed by eCAL HDF5 API and therefore the information is also not visible for the user or in your case the ecal meas cutter. For this reason we introduced this very generic named "MEASUREMENT_CONVERTER" folder, where we just save the entire hdf5 output in one single flat structure. 

On short notice I can offer you that we fix the location of ecalmeas file as well as the doc folder. So that we end up something like:

- doc
- MEASUREMENT_CONVERTER
    - *.hdf5
- *.ecalmeas

Let me know if this is already sufficiant in your case.

Due to the reasons that I described above, reflecting the sub folder names in the convertered output will require changes in the architecture how we load folder structures of hdf5 files, either inside meas cutter or even in eCAL HDF5.
