### ISSUE TITLE
eCAL HDF5: Split-Size option is broken

### ISSUE THREAD

**Issue by FlorianReimold** [eclipse-ecal/ecal#802]
# Bug

Since the one-file-per-channel option was introduced, eCAL HDF5 fails to split the HDF5 files. This issue exists in the API itself and in the eCAL Recorder.

I assume, the issue exists somewhere around here:
https://github.com/eclipse-ecal/ecal/blob/fd4295852bfc09cb78d1f6c5db1c9f5a020a5242/contrib/ecalhdf5/src/eh5_meas_file_writer_v5.cpp#L330

# To Reproduce

1. Set the split-size in eCAL Rec to something small
2. Record a big topic with eCAL REc
3. The files are not splitted any more

![MicrosoftTeams-image (12)](https://user-images.githubusercontent.com/11774314/192480301-4ab6172e-b75e-41fd-ae60-a567d209f484.png)
![MicrosoftTeams-image (11)](https://user-images.githubusercontent.com/11774314/192480310-d95ce6e6-4a87-4537-9f37-ce37c39cbac2.png)

# Environment

- eCAL Master (2022-09-27)
- Windows, but probably any other OS as well

**Comment by adriana-chirila** [comment]
After analyzing the issue, the problem seems to be caused by converting the splitsize into bytes twice.
Once here `void eCAL::eh5::HDF5MeasDir::SetMaxSizePerFile(size_t size)` and here 
`void eCAL::eh5::HDF5MeasFileWriterV5::SetMaxSizePerFile(size_t size)`.
One fix for it would be to modify the API to do not convert it twice.
The other solution which is better for consistency is to modify the call for the second method in such a way that is receives the size in MB.

**Comment by FlorianReimold** [comment]
I think both classes inherit from the same abstract interface class, so they must have the same API. So I think your latter idea is the proper way to fix it.

If you are already at it, maybe you could also incorporate the unit in the parameter name, e.g. by renaming it to `max_file_size_mib` or similar.
