### ISSUE TITLE
Access violation for HDF5Meas GetEntryData using proto message

### ISSUE THREAD

**Issue by oskr1709** [eclipse-ecal/ecal#887]
**Describe the bug**
Previously I was working with ecal player but now I need to use the class HDF5Meas to read the hdf5 files directly. I´m retrieving the channel and entries but I can´t get the entries data, that is a osi3::SensorData (basically a protobuf message). It is causing an access violation. 

**To Reproduce**

```
#include <ecalhdf5/eh5_meas.h>
#include <osi_sensordata.pb.h>

eCAL::eh5::HDF5Meas HDF5_Measurement(path, eCAL::eh5::RDONLY);
std::set<std::string> channelnames;
channelnames = HDF5_Measurement.GetChannelNames();
eCAL::eh5::EntryInfoSet Info_Set;
for (auto const &channel : channelnames) {
           HDF5_Measurement.GetEntriesInfo(channel, Info_Set);
	   for (auto &entry : Info_Set) {
				osi3::SensorData* sensordata_in;
				HDF5_Measurement.GetEntryData(entry.ID, sensordata_in);// Access violation reading location 
          }
}
```

**Expected behavior**
No exception thrown and retrieving the data for each entry

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10

**Comment by rex-schilasky** [comment]
Hi @oskr1709, if you want to read out protobuf channels you can use the `eCAL::measurement::IMeasurement` API. See the [measurement_read sample](https://github.com/eclipse-ecal/ecal/blob/master/samples/cpp/measurement/measurement_read/src/measurement_read.cpp),

The access violation in your sample is caused by the uninitialized pointer `osi3::SensorData* sensordata_in`. You need to preallocate the memory by the size given by the `eCAL::eh5::HDF5Meas::GetEntryDataSize` interface function.

**Comment by oskr1709** [comment]
Thank you very much! With the  eCAL::measurement::IMeasurement API was much more directly. Now It is reading the hdf5 files without any problem. Thanks!
