### ISSUE TITLE
How to: Multiple Publisher to Single Subscriber 

### ISSUE THREAD

**Issue by BriFuture** [eclipse-ecal/ecal#930]
**Is your feature request related to a problem? Please describe.**
How to map multiple publisher with same topic name into single subscriber (Many to One) or (Many to Many) in the same machine?

For example, I create two publisher, `Pub1` and  `Pub2`, one subscriber `Sub1`, all of them use topic `/test/topic`,
then I get warning when using ecal_mon_gui: 2 publishers,

Is that Ok if I put multiple publisher in single machine?  Will that cause some unexpected behaviour?

Which is the best way to achieve Many to One mode or Many to Many pub/sub mode.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by KerstinKeller** [comment]
Hi @BriFuture ,

It is totally ok to have multiple publishers.
This warning in eCAL monitor was added only because we had scenarios, where we unintentionally had two publishers for the same topic and users wanted to be made aware of it.
But from eCAL point of view, it's totally ok to have Many to One / Many to Many scenarios.
